[project]
name = "fengdock"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.0",
    "fastapi>=0.120.3",
    "httpx>=0.28.1",
    "sqlalchemy>=2.0.44",
    "uvicorn[standard]>=0.38.0",
]
